package org.sgutierr.brms.crud.model;

rule "PaymentInWhiteList"
    lock-on-active true
    ruleflow-group "list-rules"
    salience 4
	when
		$payment:Insured()
		whiteList:WhiteList( whiteList.accountNumbers contains $payment.insuranceNumber ) 		
	then 
   modify($payment){setDecision( "approved" )};
      modify($payment){setScore($payment.getScore()+100)};
		        modify($payment){setRulesOutcome( "Valid  CCN, it's in White List " +$payment.getId()+" "+$payment.getName())};
 System.out.println("Valid  CCN, it's in White List "+$payment.getId()+" "+$payment.getName()); 
end
