	import org.sgutierr.brms.crud.model.Insured;
		
		rule "VALIDATE_MAIL"
			  lock-on-active true
                ruleflow-group "prevalidations"
                  dialect "mvel"
		    when
		      $payment:Insured(  email contains "@xxx.com"  )
		    then
                        modify($payment){setDecision("rejected"  )};
                        modify($payment){setScore( $payment.getScore()-45 )};
		        modify($payment){setRulesOutcome( "We don't trusted in that email domain, it belongs of black list domains " +$payment.getId()+" "+$payment.getName())};
 System.out.println("Rule all fired for this fact - invalid email domain"+$payment.getId()+" "+$payment.getName()); 
                        
		end