	import org.sgutierr.brms.crud.model.Insured;
		
		rule "VALIDATE_AMERICAN_EXPRESS"
		  lock-on-active true
                   ruleflow-group "prevalidations"
		    when
		      $payment:Insured( insuranceNumber matches "2.*" , nif == "American Express" )
		    then
                        modify($payment){setDecision( "rejected"  )};
                        modify($payment){setScore( $payment.getScore()-100 )};
		        modify($payment){setRulesOutcome( "Invalid number for American Express " +$payment.getId()+" "+$payment.getName())};
 System.out.println("Rule all fired for this fact"+$payment.getId()+" "+$payment.getName());                         
		end