package org.sgutierr.brms.frauddetection;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(7d6e07732fc33a52b4faf4fd5a0e8695)
 */
@org.kie.api.definition.type.Label(value = "entidad1_1_2")
public class entidad1_1_2  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "att1")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String att1;

    public entidad1_1_2() {
    }

    public entidad1_1_2(java.lang.String att1) {
        this.att1 = att1;
    }


    
    public java.lang.String getAtt1() {
        return this.att1;
    }

    public void setAtt1(java.lang.String att1) {
        this.att1 = att1;
    }
}