package org.sgutierr.brms.frauddetection;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(364c977c5b980a66ae98041f102121c9)
 */
@org.kie.api.definition.type.Label(value = "Payment")
public class PaymentBC  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "company")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String company;
    
    @org.kie.api.definition.type.Label(value = "CountryCC")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String countryCC;
    
    @org.kie.api.definition.type.Label(value = "Location order")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String countryOrder;
    
    @org.kie.api.definition.type.Label(value = "Date")
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.Date date;
    
    @org.kie.api.definition.type.Label(value = "NumberCC")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String number;

    public PaymentBC() {
    }

    public PaymentBC(java.lang.String number, java.lang.String company, java.lang.String countryCC, java.lang.String countryOrder, java.util.Date date) {
        this.number = number;
        this.company = company;
        this.countryCC = countryCC;
        this.countryOrder = countryOrder;
        this.date = date;
    }


    
    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    
    public java.lang.String getCountryCC() {
        return this.countryCC;
    }

    public void setCountryCC(java.lang.String countryCC) {
        this.countryCC = countryCC;
    }
    
    public java.lang.String getCountryOrder() {
        return this.countryOrder;
    }

    public void setCountryOrder(java.lang.String countryOrder) {
        this.countryOrder = countryOrder;
    }
    
    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }
    
    public java.lang.String getNumber() {
        return this.number;
    }

    public void setNumber(java.lang.String number) {
        this.number = number;
    }
}